// ─────────────────────────────────────────────
// Chef Nutri-Kid — Freemium Gate
// Codes generated by admin are stored in localStorage
// under key cnk_valid_codes (array of strings)
// ─────────────────────────────────────────────

const KEYS = {
  recipeUsed: 'cnk_recipe_used',
  isPremium:  'cnk_is_premium',
  planType:   'cnk_plan_type',
  planExpiry: 'cnk_plan_expiry',
  userData:   'cnk_user_data',
  validCodes: 'cnk_valid_codes',   // array of valid codes saved by admin
  usedCode:   'cnk_used_code',     // the code this user entered
  referCode:  'cnk_refer_code',    // referral code used
  childProfiles: 'cnk_child_profiles',
};

// ── Static fallback codes (always valid) ──
const STATIC_CODES = [
  'NUTRI-STARTER','NUTRI-FAMILY','NUTRI-PREMIUM',
  'CNK2026-S','CNK2026-F','CNK2026-P',
  'MASTER-OVERRIDE-2026',
];

export const freemium = {
  markUsed(): void {
    localStorage.setItem(KEYS.recipeUsed, 'true');
  },

  hasUsedFree(): boolean {
    return localStorage.getItem(KEYS.recipeUsed) === 'true';
  },

  isPremium(): boolean {
    // Check expiry
    const expiry = localStorage.getItem(KEYS.planExpiry);
    if (expiry && new Date(expiry) < new Date()) {
      // Plan expired — revoke premium
      localStorage.setItem(KEYS.isPremium, 'false');
      return false;
    }
    return localStorage.getItem(KEYS.isPremium) === 'true';
  },

  getPlanType(): string {
    return localStorage.getItem(KEYS.planType) || 'free';
  },

  getMaxChildren(): number {
    const plan = this.getPlanType();
    if (plan === 'premium') return 999;
    if (plan === 'family') return 3;
    if (plan === 'starter') return 1;
    return 0;
  },

  getUserData(): any {
    try {
      return JSON.parse(localStorage.getItem(KEYS.userData) || '{}');
    } catch { return {}; }
  },

  // Admin registers valid codes into localStorage so any device can check
  // The admin panel calls this when generating a code
  getValidCodes(): string[] {
    try {
      return JSON.parse(localStorage.getItem(KEYS.validCodes) || '[]');
    } catch { return []; }
  },

  addValidCode(code: string): void {
    const codes = this.getValidCodes();
    if (!codes.includes(code.toUpperCase())) {
      codes.push(code.toUpperCase());
      localStorage.setItem(KEYS.validCodes, JSON.stringify(codes));
    }
  },

  unlock(code: string, userData?: {name?: string, phone?: string, email?: string, plan?: string, expiry?: string}): boolean {
    const c = code.trim().toUpperCase();
    const dynamicCodes = this.getValidCodes();
    const isValid = STATIC_CODES.includes(c) || dynamicCodes.includes(c) || c.startsWith('CNK-');

    if (isValid) {
      localStorage.setItem(KEYS.isPremium, 'true');
      localStorage.setItem(KEYS.usedCode, c);

      // Determine plan from code
      let plan = 'starter';
      if (c.includes('FAM') || c.includes('FAMILY') || c.includes('-F-')) plan = 'family';
      else if (c.includes('PRE') || c.includes('PREMIUM') || c.includes('-P-')) plan = 'premium';
      localStorage.setItem(KEYS.planType, userData?.plan?.toLowerCase() || plan);

      // Set expiry
      if (userData?.expiry) {
        localStorage.setItem(KEYS.planExpiry, userData.expiry);
      }

      // Save user data
      if (userData) {
        localStorage.setItem(KEYS.userData, JSON.stringify(userData));
      }

      return true;
    }
    return false;
  },

  reset(): void {
    [KEYS.recipeUsed, KEYS.isPremium, KEYS.planType, KEYS.planExpiry, KEYS.userData, KEYS.usedCode].forEach(k => localStorage.removeItem(k));
  },

  canGenerate(): boolean {
    return this.isPremium() || !this.hasUsedFree();
  },

  canAccessPremium(): boolean {
    return this.isPremium();
  },
};
